# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecf3951d26fb714a1bd36036066ebf6e2fd11851140645405260315a1eb4c91c69159e5404a32a9f330e62667352f54bc4e0de9de8ece35a7a26dab2ce364306

test:
  secret_key_base: 26d3caae6aedbc12eb00b408d387b36a525982c23dd3097cc99742e0b2ee0e83b17cfb00e9826bb7e4b05ba64fea3f094c907e6b1c002f1ca9c6beaf00325faa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
